import { CHAT_PERMISSIONS, DEFAULT_ROLES } from '@repo/utils/db';

export const DEFAULT_ROLES_PERMISSIONS: Record<
  DEFAULT_ROLES,
  CHAT_PERMISSIONS[]
> = {
  [DEFAULT_ROLES.OWNER]: Object.values(CHAT_PERMISSIONS),
  [DEFAULT_ROLES.USER]: [
    CHAT_PERMISSIONS.MESSAGE_DELETE,
    CHAT_PERMISSIONS.MESSAGE_EDIT,
    CHAT_PERMISSIONS.MESSAGE_MEDIA_CREATE,
    CHAT_PERMISSIONS.MESSAGE_TEXT_CREATE,
    CHAT_PERMISSIONS.USER_ADD,
  ],
};
